name: Swift

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Format & Commit
      uses: damuellen/gha-swift-format@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
